BACKEND: virtual
SCHEDULE:
  FUSE_BN: True
W:
  QSCHEME: per-group-affine
  QUANTIZER:
    TYPE: uniform
    BIT: 4
    GROUP_SIZE: 8
  OBSERVER:
    TYPE: MSE
  SPECIFIC: [{
    "model_0_conv": ["QUANTIZER.BIT", 8, "OBSERVER.TYPE", "MINMAX", "QSCHEME", "per-channel-affine", "QUANTIZER.GROUP_SIZE", -1],
    "model_24": ["QUANTIZER.BIT", 8, "OBSERVER.TYPE", "MINMAX", "QSCHEME", "per-channel-affine", "QUANTIZER.GROUP_SIZE", -1],
    "model_25": ["QUANTIZER.BIT", 8, "OBSERVER.TYPE", "MINMAX", "QSCHEME", "per-channel-affine", "QUANTIZER.GROUP_SIZE", -1],
    "model_26": ["QUANTIZER.BIT", 8, "OBSERVER.TYPE", "MINMAX", "QSCHEME", "per-channel-affine", "QUANTIZER.GROUP_SIZE", -1],
  }]
  BIAS_CORRECTION: True
A:
  QSCHEME: per-tensor-affine
  QUANTIZER:
    TYPE: pwlq
    BIT: 4
  OBSERVER:
    TYPE: MSE
    LAYOUT: NCHW
  SPECIFIC: [{
    "model_0_conv": ["QUANTIZER.DISABLE", True, "QUANTIZER.BIT", 8, "OBSERVER.TYPE", "MINMAX", "QSCHEME", "per-tensor-affine", "QUANTIZER.GROUP_SIZE", -1],
    "model_24": ["QUANTIZER.BIT", 8, "OBSERVER.TYPE", "MINMAX", "QSCHEME", "per-tensor-affine", "QUANTIZER.GROUP_SIZE", -1],
    "model_25": ["QUANTIZER.BIT", 8, "OBSERVER.TYPE", "MINMAX", "QSCHEME", "per-tensor-affine", "QUANTIZER.GROUP_SIZE", -1],
    "model_26": ["QUANTIZER.BIT", 8, "OBSERVER.TYPE", "MINMAX", "QSCHEME", "per-tensor-affine", "QUANTIZER.GROUP_SIZE", -1],
  }]

